# Generated by Django 3.2.9 on 2021-12-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChairID', models.IntegerField(max_length=200)),
                ('status', models.BooleanField(verbose_name='Occupation Status')),
            ],
        ),
    ]
