# Generated by Django 3.2.9 on 2021-12-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChairApp', '0002_alter_chairs_chairid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chairs',
            new_name='Chair',
        ),
    ]
