# Generated by Django 3.2.9 on 2022-03-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairApp', '0003_rename_chairs_chair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalChairs', models.IntegerField(verbose_name='Total Chairs')),
                ('occupiedChairs', models.IntegerField(verbose_name='Occupied Chairs')),
            ],
        ),
        migrations.DeleteModel(
            name='Chair',
        ),
    ]
