# Generated by Django 3.2.9 on 2022-03-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairApp', '0004_auto_20220318_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
