# Generated by Django 3.2.9 on 2022-03-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChairApp', '0005_room_roomname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomName',
        ),
    ]
