# Generated by Django 3.2.9 on 2022-03-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairApp', '0006_remove_room_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomName',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
