# Generated by Django 3.2.9 on 2022-04-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairApp', '0007_room_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomID',
            field=models.IntegerField(default=0, verbose_name='Room ID'),
            preserve_default=False,
        ),
    ]
