# Generated by Django 3.2.9 on 2022-04-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChairApp', '0008_room_roomid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomID',
        ),
    ]
